access_key_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("api.urls", namespace="api")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("main.urls", namespace="main")),
    # PASSWORD RESET VIEWS
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password_reset_form.html"
        ),
        name="password_reset",
    ),
    path(
        "password_reset_done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/new_password_form.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("verification/", include("verify_email.urls")),
] + staticfiles_urlpatterns()

accounts/urls.py
from django.urls import path
from accounts import views


app_name = "accounts"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login_page"),
    path("register/", views.RegisterView.as_view(), name="register_view"),
    path("logout/", views.LogoutView.as_view(), name="logout_view"),
]

api/urls.py
from rest_framework.urls import path
from api import views

app_name = "api"

urlpatterns = [
    path(
        "accounts/details",
        views.AccountsDetails.as_view(),
        name="accouts_details",
    ),
]

main/urls.py
from django.urls import path
from main import views


app_name = "main"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("request_key/<uuid>", views.RequestKeyView.as_view(), name="request_key"),
]

main/models.py
from datetime import timedelta
from django.db import models
from django.dispatch import receiver
from accounts.models import User
from django.db.models.signals import pre_save
import uuid, random
from django.utils import timezone
from django.utils import timezone
from django.db import models


# ACCESS KEYS FOR USERS
class AccessKey(models.Model):
    class KeyStatus(models.TextChoices):
        REVOKED = ("REVOKED", "Revoked")
        ACTIVE = ("ACTIVE", "Active")
        EXPIRED = ("EXPIRED", "Expired")

    key = models.UUIDField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    expiry_date = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    status = models.CharField(
        max_length=10, choices=KeyStatus.choices, default=KeyStatus.ACTIVE
    )

    def check_expiry(self):
        for key in AccessKey.objects.all():
            if key.expiry_date < timezone.now():
                key.status = AccessKey.KeyStatus.EXPIRED
                key.save()
                
                return key


# SET EXPIRY DATE AND KEY ON SAVE
@receiver(pre_save, sender=AccessKey)
def save_key_data(sender, instance, *args, **kwargs):
    if instance:
        instance.expiry_date = timezone.now() + timedelta(seconds=5)
        instance.key = uuid.uuid4()


# MANAGER TO CREATE KEY TOKEN
class KeyTokenManager(models.Manager):
    def create(self, **kwargs):
        instance = self.model(
            key="AKM_ACKY" + str(random.randrange(start=100, stop=10000)), **kwargs
        )
        instance.save()
        return instance


# KEYTOKENS TO BE SENT TO USERS FOR GENERATING ACCESS KEYS
class KeyToken(models.Model):

    class Status(models.TextChoices):
        ACTIVE = ("ACTIVE", "Active")
        EXPIRED = ("EXPIRED", "Expired")

    key = models.CharField(
        blank=True,
        null=True,
        unique=True,
        max_length=100,
        db_index=True,
    )
    created_at = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(
        max_length=10, default=Status.ACTIVE, choices=Status.choices
    )

    objects = KeyTokenManager()

main/views.py
from django.shortcuts import redirect, render
from django.views.generic import View
from accounts.models import User
from main.models import AccessKey, KeyToken
from main.services import LoginMixin, send_key_token
from django.contrib import messages


class HomeView(LoginMixin, View):
    def get(self, request):
        # GET ACTIVE, REVOKED AND EXPIRED KEYS
        # AccessKey.check_expiry(self)

        active_keys = AccessKey.objects.filter(user=request.user, status="ACTIVE")
        revoked_keys = AccessKey.objects.filter(user=request.user, status="REVOKED")
        expired_keys = AccessKey.objects.filter(user=request.user, status="EXPIRED")

        ctx = {
            "active_keys": active_keys,
            "revoked_keys": revoked_keys,
            "expired_keys": expired_keys,
        }
        return render(request, "main/home.html", ctx)

    def post(self, request):
        key = AccessKey.objects.get(user=request.user)
        return render(request, "main/home.html", {"key": key})


class RequestKeyView(LoginMixin, View):
    def get(self, request, uuid):
        user = User.objects.get(id=uuid)
        send_key_token(user=user)
        ctx = {
            "user": user,
        }
        return render(request, "main/request_key.html", ctx)

    def post(self, request, uuid):

        token = request.POST["token"].strip(" ")

        # CHECK IF TOKEN AND USER EXISTS
        try:
            user = User.objects.get(id=uuid)
            acces_token = KeyToken.objects.get(key=token)
            if acces_token.status == "EXPIRED":
                messages.error(request, "Token has expired!")
                return render(request, "main/request_key.html", {"user": user})

        except Exception as e:
            messages.error(request, f"{e}")
            return render(request, "main/request_key.html", {"user": user})

        # CHECK IF TOKEN BELONGS TO USER
        if acces_token.user == user:
            keys = AccessKey.objects.filter(user=user)
            for key in keys:
                # CHECK IF CURRENT KEY IS ACTIVE
                if key.status == "ACTIVE":
                    messages.error(request, "Current key is not expired yet!")
                    return redirect("main:home")

            # CREATE NEW KEY
            new_key = AccessKey.objects.create(user=user)
            new_key.clean()
            new_key.save()

            # SET TOKEN STATUS TO EXPIRED
            acces_token.status = "EXPIRED"
            acces_token.save()
            return redirect("main:home")
        messages.error(request, "an error occured")
        return render(request, "main/request_key.html", {"user": user})

templates/main/home.html
{% extends "base.html" %}

{% block title %}
Home
{% endblock title %}

{% block nav %}
{% include "main/nav.html" %}
{% endblock nav %}

{% block content %}
<main>
    {% if request.user.is_authenticated %}
    <main>
        <div class="card mx-5 my-3">
            <div class="card-header" style="color: green;">
                Active keys
            </div>
            <div class="card-body p-2 m-2">
                {% for key in active_keys %}
                <p class="card-text">{{key.key}}</p>
                <p class="card-text blockquote-footer">{{key.created_at}} | {{key.expiry_date}}</p>
                {% empty %}
                <a href="{% url 'main:request_key' request.user.id %}" class="btn btn-primary btn-sm">Request
                    key</a>
                {% endfor %}
            </div>
        </div>

        <div class="card mx-5 my-3">
            <div class="card-header" style="color: rgb(173, 114, 4);">
                Revoked keys
            </div>
            <div class="card-body p-2 m-2">
                {% for key in revoked_keys %}
                <p class="card-text">{{key.key}}</p>
                <p class="card-text blockquote-footer">{{key.created_at}} | {{key.expiry_date}}</p>
                {% empty %}
                <p>No item...</p>
                {% endfor %}
            </div>
        </div>

        <div class="card mx-5 my-3">
            <div class="card-header" style="color: rgb(179, 28, 28);">
                Epired keys
            </div>
            <div class="card-body p-2 m-2">
                {% for key in expired_keys %}
                <p class="card-text">{{key.key}}</p>
                <p class="card-text blockquote-footer">{{key.created_at}} | {{key.expiry_date}}</p>
                {% empty %}
                <p>No item...</p>
                {% endfor %}
            </div>
        </div>

    </main>
    {% endif %}
</main>
{% endblock content %}

templates/main/nav.html
<nav>
  <ul class="nav justify-content-center">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'main:home' %}">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'accounts:logout_view' %}">Logout</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/" style="color: rgb(30, 29, 29);">{{request.user}}</a>
    </li>
  </ul>
</nav>
<hr>

templates/main/request_key.html
{% extends "base.html" %}

{% block title %}
Request Key
{% endblock title %}

{% block nav %}
{% include "main/nav.html" %}
{% endblock nav %}

{% block content %}
<main>
    <form class="form text-center m-5" action="{% url 'main:request_key' user.id %}" method="post">
        {% csrf_token %}
        <p>
            Please enter the key token sent to your email <bold>{{user.email}}</bold> to generate a new Access Key.
        </p>
        <p>
            <input type="text" name="token" placeholder="Key Token" autocomplete="on" required class="form-control m">
        </p>
        <input type="submit" value="Request Key" class="btn btn-primary btn-sm">
    </form>
</main>
{% endblock content %}