access_key_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("api.urls", namespace="api")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("main.urls", namespace="main")),
    # PASSWORD RESET VIEWS
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password_reset_form.html"
        ),
        name="password_reset",
    ),
    path(
        "password_reset_done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/new_password_form.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("verification/", include("verify_email.urls")),
] + staticfiles_urlpatterns()

accounts/urls.py
from django.urls import path
from accounts import views


app_name = "accounts"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login_page"),
    path("register/", views.RegisterView.as_view(), name="register_view"),
    path("logout/", views.LogoutView.as_view(), name="logout_view"),
]

api/urls.py
from rest_framework.urls import path
from api import views

app_name = "api"

urlpatterns = [
    path(
        "accounts/details",
        views.AccountsDetails.as_view(),
        name="accouts_details",
    ),
]

templates/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <title>
    {% block title %}

    {% endblock title %}
  </title>
</head>

<body>
  <header>
    {% block nav %}

    {% endblock nav %}
  </header>


  <section>
    {% if messages %}
    <div class="alert alert-primary">
      <ul class="messages" style="height: 0.1rem;">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}
  </section>
  {% block content %}

  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>

  <script>
    // close message notification after three seconds
    setTimeout(() => {
      document.querySelector('.alert').style.display = 'none';
    }, 5000);
  </script>
</body>

</html>

templates/nav.html
<nav>
  <ul class="nav justify-content-center">

    {% if request.user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'accounts:logout_view' %}">Logout</a>
    </li>
    {% else %}
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="{% url 'accounts:register_view' %}">Register</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'accounts:login_page' %}">Login</a>
    </li>
    {% endif %}

  </ul>
</nav>
<hr>